### ISSUE TITLE
How to update a specific chunk?

### ISSUE THREAD

**Issue by raoneel** [andyhall/noa#94] opened 2020-01-13 22:51 UTC
Hey, I'm wondering what the best way to update a specific chunk (lot's of updates). For context, I'm working on a multiplayer game.

1. Multiple users are in the same world, placing block updates
2. Periodically, the client refreshes by downloading entire chunks from the server
3. Let's say a user is in chunk A, and they want to see the latest version. They download the freshest copy of chunkA from the server.
4. How would I "update" or "refresh" chunkA with a completely different chunk Array? Would I just remove and then add it back to the chunking queue? Is there another method I can call?

**Comment by andyhall** [comment] 2020-01-14 04:45
Hi, sorry I haven't moved on your other issue yet. In thinking about it, I came to realize that working with updates from multiple clients is never going to work unless I get rid of the duplicated one-voxel padding between chunks, so I'm working on getting rid of that right now.

Once that's done, what do you think the ideal API would be here? I think the setup I talked about in your other thread may just be overcomplicated; you may have clearer ideas on this than I do. 

E.g., I guess the simplest solution would be if there was an API for the game client to say "hey, invalidate all voxels in the following AABB". Then the engine marks all chunks that overlap that AABB for removal, they later get disposed, and then it will issue new "dataNeeded "events for whichever chunks are still in range, and the client can reply with new data as usual. Would that fit the bill?

**Comment by raoneel** [comment] 2020-01-14 07:18
That's great news about removing the padding, that will be really helpful! Thanks!

I think "invalidate all voxels in the following AABB" makes a ton of sense . It gives the client control over when to update specific areas and how large the area should be.

For a multiplayer setup, there are (at least) two types of updates you can get. One is just when users place individual blocks. This is fine because you can just call noa.addBlock.

However, with lots of players, it might be expensive/unfeasible to send every single block update from every other user. In this case, you might want to do something like "update an entire chunk". Maybe closer chunks get updated more frequently, and ones further away less frequently because you can't see them. This helps with performance because instead of getting 1000 add block  events (from other players) in 1 second for the same chunk, you could just get the entire chunkData instead, saving a lot on both network and probably rendering.

Your proposal above should solve this use-case. I hope my explanation makes sense!

**Comment by andyhall** [comment] 2020-01-14 09:11
Ok, it sounds like we're on the same wavelength!

The wrinkle that I was trying to think about is, it would be nice to minimize the need for your game client to store duplicate voxel data, that it got from the server and it's waiting for noa to request. Also note that you'll definitely have cases where you get a chunk of data from the server and tell noa to invalidate it, but noa never actually requests that chunk (because the player moved out of range while the work was queued), so your client will probably need to detect that and eventually dispose of the data. These kinds of issues are the reason I was thinking about a more complicated solution, in that other thread.

But thinking about it now, I think that would create too much coupling between noas internals and your server/client, whereas the suggestion above leaves you pretty free to do your tracking per-voxel or per-chunk or a mix of the two. And you could always minimize storage by having your server send data in RLE-encoded chunks, which your client could then just decode directly into noa's request array, avoiding too much duplication.

It will take me a bit of time to get the unpadded meshing working, so do let me know if you have other ideas. Once that's working I'll release it as 0.28, if you'd like to plan around that.

**Comment by andyhall** [comment] 2020-01-17 07:23
Hi @raoneel, FYI I seem to have this working already. I'm as surprised as anyone.

So, the build I just pushed to #develop no longer duplicates voxels at chunk borders, and also adds `noa.world.invalidateVoxelsInAABB`. Please let me know if you have feedback!

Side note: normally when a chunk passes out of range `noa` emits `chunkBeingRemoved`, in case the client wants to save the data. But I implemented the invalidate API as an exception to that rule, so no event will be emitted for the chunks that get removed as invalid. I'm guessing you probably don't use the events either way, but just in case let me know if that's not what you expected to happen.

Thanks!

**Comment by raoneel** [comment] 2020-01-18 07:11
Awesome, that was really fast! Thanks! 

I've tested the duplicate voxels and confirmed that it does work! The invalidateVoxelsInAABB works as well, but I have some feedback on the functionality:

- Once you invalidate chunks, it doesn't get re-added to the queue until you move again.
- If you happen to be inside of the chunks that are invalidated, then you cannot move. And since you can't move, then the chunks are never created again.
- Is it possible to invalidate the chunks without removing it? It is a bit jarring to see everything disappear and then re-appear. Would be cool if it could just "update in place." Imagine a setup where the client wants to update the world every 5 minutes. With the current implementation, the whole world would disappear and then reappear every 5 minutes. I imagine this might be hard with the way you have the queues set up.
- One minor thing, I noticed the chunkIds are now x|y|z|worldName which did throw off a system I had in place which used the chunkId to store data. Easy fix on my end, but would be worth adding that change to the documentation (if you haven't already!)

Anyway, really appreciate the work here and let me know if I could help out in any way!

**Comment by andyhall** [comment] 2020-01-19 06:29
Hi,

On point 3, whoops, I didn't think it out but that's definitely the right thing to do. I just pushed a build that does this, can you try it out? It now updates chunks in place instead of removing/re-adding them. This *usually* happens in the same tick, but there will be cases where a chunk mesh may disappear for one frame when it's updated. (this is unavoidable for now, or at least not easy to avoid.)

On point 4: that change is unrelated to the padding thing, it's to support multiple "worlds" of data (like the overworld and nether in minecraft). However at least in principle, that `id` string is meant to be simply "a unique chunk identifier" that the game client can use as a key to store/retrieve world data, so the content of the string isn't documented. The goal is I want to avoid coupling how the client does worldgen and now noa internally stores data, as much as possible. 

But I haven't fully thought out the needs of multiuser servers (as I'm sure you've noticed), so if absolutely need the content of that string id to be documented/predictable, can you make another issue to explain why? Maybe we can work out what API is missing and add it.

**Comment by andyhall** [comment] 2020-01-19 06:39
On point 1/2 - that's a problem but I can't reproduce it. It's intentional that most game systems (physics etc.) stop working when the player's current chunk isn't in memory, but worldgen keeps running, so normally the missing chunks should get requested and created very quickly.

Can you check if this still happens in the build I pushed and investigate further? Poking around these internals should probably give some idea what's happening.

```js
noa.world.report()   // summarizes what's in the various queues
noa.world._chunkIDsKnown = []       // all chunks existing in any queue
noa.world._chunkIDsToRequest = []   // not yet requested from client
noa.world._chunkIDsPending = []     // requested, awaiting creation
noa.world._chunkIDsToMesh = []      // waiting to be (re)meshed
noa.world._chunkIDsToMeshFirst = [] // priority meshing queue
noa.world._chunkIDsToRemove = []    // chunks awaiting disposal
```

If the issue still happens in the latest build, can you open a new issue for it, and describe how to reproduce, and what's going on in those queues when it happens?

thanks!

**Comment by raoneel** [comment] 2020-01-20 09:41
Awesome! Just tested it out and it worked great!

Re: chunkIds. I think your approach now is fine. I was just using it as a key in my database to store the run-length-encoded chunk data. I don't think you need to make any changes on your end. For me, I should probably use something like x|y|z as the key in storage, and manually generate this key instead of relying on the internal chunkId.

Re: Chunks not re-appearing and player freezing bugs. They are both not reproducible for me with your newest changes. Thanks!

If it's possible that the chunk disappears for one frame, could the player freeze if they're in the chunk during that one frame? I'm not able to test that case specifically, but I'm wondering if that could happen. Otherwise, it all seems good!

**Comment by andyhall** [comment] 2020-01-20 14:24
Hi, thanks for checking!

On the ids, they're just meant to be unique identifiers, so if the engine requests data with an ID, future requests (or "chunkBeingRemoved" events) with the same ID will be the same region. But if you're doing a server I guess you naturally need to do more granular handling, so as not to update a whole chunk when one voxel changes (or vice versa). I haven't done any hard thinking about this but open to suggestions of course.

On the last point, in that particular case the player wouldn't freeze. The engine pauses game time when the player's chunk isn't in memory (since physics etc. can't work without terrain data). But in the case we're talking about the chunk data is never missing, it's just the visual mesh may disappear for one frame while it's being recreated. Hope that makes sense.

Thanks again!

**Comment by raoneel** [comment] 2020-01-23 04:51
On my server, I store each chunk separately, keyed by chunkID. In worldDataNeeded, I do a network request to get all the chunk data for a given chunkID. The chunkID is a convenient way to refer to a specific chunk on my server. Depending on how you store data on your server, you may need a different chunkID, nor may not need one at all. So I don't think the noa engine should necessarily use a specific chunkID just to enable server use-cases. Clients can manually construct whatever chunkID they want using the x,y,z coordinates of the chunk, also given in worldDataNeeded.

**Comment by raoneel** [comment] 2020-01-26 08:28
Hey @andyhall,

I was doing some testing with invalidateVoxelsInAABB and I believe I am seeing a short lag spike when using the method. This happens even when invalidating one single chunk. I was wondering if you were seeing the same thing? I am testing this by setting an interval like this:

`setInterval(() => {
  let box = {
    base: [0, 0, 0],
    max: [49, 49,49]
  }

  noa.world.invalidateVoxelsInAABB(box)
}, 5000);`

And observing a quick lag spike every 5 seconds, even when standing still. I haven't had a chance to dig into the engine source code yet to see why, but wanted to let you know about it

**Comment by raoneel** [comment] 2020-01-26 08:40
^Actually, ignore that comment. I think it was just an issue with my computer. Not able to re-create it now haha.

**Comment by andyhall** [comment] 2020-01-26 17:21
Okay, yeah... there could definitely be perf gotchas somewhere, but all the invalidate API itself does is iterate once through all the chunks in memory. Thanks again for testing!

**Comment by andyhall** [comment] 2020-01-30 09:59
Closing this since v0.28 is pushed. Open a new issue if anything's amiss!

**Closed by andyhall** 2020-01-30 09:59 UTC
Labels: enhancement

**Comment by Jarred-Sumner** [comment] 2020-04-17 20:14
Some code that might be useful as a point of reference for future multiplayer-related issues: 

https://github.com/PrismarineJS/flying-squid/blob/5746fd4ef28b73c56fd80dede2d830d2537ed664/src/lib/plugins/world.js#L128-L140

`flying-squid` is an open source Minecraft server written in JS. 

In their implementation, chunks are ID'd by `(X,Z / 16)`. As soon as a player authenticates successfully, the server [sets a spawn location](https://github.com/PrismarineJS/flying-squid/blob/5746fd4ef28b73c56fd80dede2d830d2537ed664/src/lib/plugins/login.js#L152-L170), starts sending them nearby chunks in a spiral fashion (probably visually looks better than straight lines), and then sends them the rest of the map.

As the player moves, the server tells the client to unload chunks and the server proactively sends chunks to the client - the client does not ask the server for chunks itself. 

The main thing I like about this approach is deterministic IDs for chunks
