### ISSUE TITLE
Frame drops with larger worlds – mergeSubmeshes slow

### ISSUE THREAD

**Issue by Jarred-Sumner** [andyhall/noa#96] opened 2020-04-20 00:52 UTC
After 15 seconds of running the profiler:
<img src="https://user-images.githubusercontent.com/709451/79704081-60c3b300-8264-11ea-8c6d-a9a0725e4f4f.png" height=300 />

Narrowing it down to a point where FPS dropped a decent amount:
<img src="https://user-images.githubusercontent.com/709451/79704133-c152f000-8264-11ea-950a-a2b5243d9a81.png" height=300 />

This is running on the latest Macbook Pro on macOS with `AMD Radeon Pro 5500M 8 GB` on latest stable Chrome

To some extent, this method is probably always going to be a little slow. But I wonder if some of this code could be moved into a web worker? That way, it won't cause frame drops. If the data is [`Transferable`,](https://developer.mozilla.org/en-US/docs/Web/API/Transferable) then there wouldn't be a performance hit from moving it to a worker, and I think it might be since its mostly a lot of numbers and arrays of numbers?

If its helpful, here's the profile: https://www.dropbox.com/s/cchbewrmn7pt1ib/Profile-20200419T173521.json.zip?dl=1. I compressed it into a .zip because my internet is slow at uploading files

**Comment by andyhall** [comment] 2020-04-20 04:22
Hi, thanks for poking around! The code here is pretty heavy, yeah - broadly it's the code that processes each chunk of voxel IDs into meshes the 3D engine can render, which means it needs to fully sweep through the whole chunk three times (for each axis). I'm not sure why `mergeSubmeshes` particularly is slow, maybe those big array concatenations could be done faster? May need to look into that.

But for the big picture, it would be ideal to do meshing in a worker but I haven't looked closely at whether it's possible. My guess is, the big complication would be that the mesher runs on each chunk's voxel ID array, and various game logic also needs to access those arrays (to do physics, etc). I guess this could be worked around by copying each chunk's voxel data (into a transferable array) so that the copy can be meshed while the real data stays where it is. My guess is that the copy would be fast compared to the meshing so it would be an overall perf improvement. But the bigger worry is that meshing is already the most complex part of the engine, and making it more complex and asynchronous is reasonably scary ;)

So, I think this may every well be worth doing but it'd be very nontrivial. But I haven't looked at it carefully, and will use this issue to track any progress.

Aside: if the FPS drop is affecting your game one option is to decrease your chunk size - which doesn't reduce the total amount of meshing in your world, but it splits the work into smaller bites. I think chunk size defaults to 24, but I use 32 and am finding the performance to be okay on old-ish hardware.

**Comment by andyhall** [comment] 2020-04-30 04:54
Hi @Jarred-Sumner, what chrome version and OS did you do your testing on?

I assume the cause of your perf issue was the calls to `Array.concat`, since the function we're looking at doesn't do anything else, and various articles from last year claim that `concat` is slow. But in some rough benchmarks, in my browser (chrome 81, OSX) `concat` is now moderately faster than the alternatives. And in an actual noa game, `mergeSubmeshes` has no perf impact (it's too fast to measure reliably compared to the rest of the terrain meshing).

So I'm guessing this is related to either your environment or the specifics of your game. Can you test and see if `mergeSubmeshes` is still slow in, say, a different browser, or with a different game world (like from `noa-examples`)?

Thanks!

**Comment by Jarred-Sumner** [comment] 2020-05-01 21:07
Thanks for investigating.

These are the options I'm passing to noa:
```typescript
 {
      debug: false,
      showFPS: true,
      chunkSize: 16,
      chunkAddDistance: 7,
      antiAlias: true,
      playerAutoStep: true,

      chunkRemoveDistance: 8,
      domElement: this.container,
      blockTestDistance: 2,
      skipDefaultHighlighting: true,
      useAO: true,
      zoomSpeed: 0.05,
      initialZoom: 3.0,

      playerHeight: Player.size.height,
      playerWidth: Player.size.width,

      playerStart: [x, y, z],
    };
```

I have the camera in a 3rd-person angle, like so:
```
camera.position.addInPlace(new Vector3(1.0, 0.1, 0.1));
noa.camera.currentZoom = 3.0;
```

I'll play around with adding/removing voxel types. A lot of these have alpha, and having AO with that might be making it slower. I'll also see if using jpg for the ones without alpha makes it faster

**Comment by andyhall** [comment] 2020-05-02 10:11
Hrm. Is `mergeSubmeshes` measurably slow all the time, or occasionally? At a guess it seems related to how v8 is optimizing the relevant code (e.g. a deopt happening or the optimizer deciding to give up or whatever), which can be pretty hard to pin down.

The only settings I'd expect to be involved would be the variety of voxels and materials getting meshed, AO, and maybe the chunk size. Things happening at render time (like what's onscreen or how the camera is set up) shouldn't matter, since world generation is long done by then. If can check whether, e.g., the issue stops or starts happening in any particular case that would help.

If the problem happens reliably and you have noa cloned locally, you might try jumping in [here](https://github.com/andyhall/noa/blob/master/src/lib/terrainMesher.js#L226-L229) and changing those `[].concat` calls into something equivalent? If it's an optimizer issue that might be what v8 isn't liking...

**Comment by Jarred-Sumner** [comment] 2020-05-03 23:13
> If the problem happens reliably and you have noa cloned locally, you might try jumping in here and changing those [].concat calls into something equivalent? If it's an optimizer issue that might be what v8 isn't liking...

That definitely makes it a lot faster!

```patch
- target.positions = target.positions.concat(mdat.positions);
- target.normals = target.normals.concat(mdat.normals);
- target.colors = target.colors.concat(mdat.colors);
- target.uvs = target.uvs.concat(mdat.uvs);

+ let posOffset = target.positions.length;
+ target.positions.length += mdat.positions.length;
+ for (let i = 0; i < mdat.positions.length; i++) {
+   target.positions[posOffset + i] = mdat.positions[i];
+ }

+ let normalsOffet = target.normals.length;
+ target.normals.length += mdat.normals.length;
+ for (let i = 0; i < mdat.normals.length; i++) {
+   target.normals[normalsOffet + i] = mdat.normals[i];
+ }

+ let colorsOffset = target.colors.length;
+ target.colors.length += mdat.colors.length;
+ for (let i = 0; i < mdat.colors.length; i++) {
+   target.colors[colorsOffset + i] = mdat.colors[i];
+ }

+ let uvsOffset = target.uvs.length;
+ target.uvs.length += mdat.uvs.length;
+ for (let i = 0; i < mdat.uvs.length; i++) {
+   target.uvs[uvsOffset + i] = mdat.uvs[i];
+ }
```

🟢 without concat:
![image](https://user-images.githubusercontent.com/709451/80927980-4e627280-8d56-11ea-85b2-5483ef87accd.png)

🔴 with concat:
![image](https://user-images.githubusercontent.com/709451/80927994-689c5080-8d56-11ea-9601-5781162ac548.png)

These were taken with the same map position chunks and noa config immediately after page load.

**Comment by andyhall** [comment] 2020-05-04 04:51
Hmm, weird! On my machine/world/etc. doing the merges with concat is slightly faster than using loops. But it's not really hot code, so I'll just get rid of the concat calls. Should be in #develop later today.

**Comment by Jarred-Sumner** [comment] 2020-05-04 04:58
Maybe it’s because I have the chunk add distance set higher than the
default

**Comment by andyhall** [comment] 2020-05-04 06:54
Hi, thanks for the PR on this. However, now that I look at this closely I've realized that the logic we're talking about was broken to begin with - the merge criteria was wrong so the first call to `mergeSubmeshes` never actually merged anything.

Anyway I've just pushed a fix to #develop (which overlaps your PR so I need to reject that, sorry). Can you check that it fixes your performance issue? I removed the calls to `concat` and also changed the merge criteria to not be a closure, so I'm guessing either/both of those changes should make sure v8 optimizes things properly.

BTW, happy to receive future PRs but please send them on the #develop branch, and check that your formatter isn't adding semicolons.  Thanks!

**Comment by Jarred-Sumner** [comment] 2020-05-04 07:16
> Hi, thanks for the PR on this. However, now that I look at this closely I've realized that the logic we're talking about was broken to begin with - the merge criteria was wrong so the first call to mergeSubmeshes never actually merged anything.

Yeah I noticed that there were two calls there and thought it seemed suspicious

No worries at all re: rejecting my PR and I'll check for semicolons in the future

I ran the latest of the `develop` branch in the profiler and walked around for a few seconds - overall, it feels a little slower I think. 
![image](https://user-images.githubusercontent.com/709451/80943476-285fc100-8d9c-11ea-80c8-091b56e48d75.png)

**Comment by Jarred-Sumner** [comment] 2020-05-04 08:00
I wonder if this is relevant: https://github.com/BabylonJS/Babylon.js/blob/master/src/Materials/multiMaterial.ts#L62

Its not a built-in `Array`, they override it to mark submeshes as dirty automatically

**Comment by andyhall** [comment] 2020-05-04 08:36
Hm. I see what you mean about the multiMaterial array, but I wouldn't think that should affect noa, since those arrays just get created once (per chunk) and then are never touched again.

I'm wondering about those big 200ms gaps though, and the time spent in StringList.remove. StringList is a struct that `noa.world` uses to manage lists of chunk ID strings, for keeping track of which chunks are loaded, need to be removed, etc, and I wouldn't think it would be a bottleneck unless there are many tens of thousands of chunks in memory (in which case, using larger chunks with a smaller chunkAddDistance would probably perform a lot better).

What kind of output do you get from `noa.world.report()`? Or alternately, if you change [this line](https://github.com/andyhall/noa/blob/master/src/lib/world.js#L6) to `1`, what kind of profile numbers do you see in the console?

**Comment by Jarred-Sumner** [comment] 2020-05-04 09:02
Running around for about 90 seconds with `chunkAddDistance` set to `6`:
```
world ticks: total 3.75ms (avg, 100 runs)     remQueue: 0.06ms    addQueue: 0.18ms    requests: 0.15ms    removes: 0.01ms    meshes: 3.32ms    looking: 0.01ms    
util.js:183 render internals total 2.76ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.02ms    render: 2.72ms    endFrame: 0.01ms    
util.js:183 world ticks: total 4.13ms (avg, 100 runs)     requests: 0.16ms    removes: 0.01ms    meshes: 3.92ms    looking: 0.03ms    
util.js:183 render internals total 1.64ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.01ms    render: 1.61ms    endFrame: 0.01ms    
util.js:183 world ticks: total 4.10ms (avg, 100 runs)     requests: 0.12ms    removes: 0.01ms    meshes: 3.95ms    looking: 0.01ms    
util.js:183 render internals total 1.62ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.01ms    render: 1.59ms    endFrame: 0.01ms    
util.js:183 world ticks: total 3.90ms (avg, 100 runs)     requests: 0.06ms    removes: 0.01ms    meshes: 3.81ms    looking: 0.01ms    
util.js:183 render internals total 1.81ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.01ms    render: 1.78ms    endFrame: 0.01ms    
util.js:183 world ticks: total 0.03ms (avg, 100 runs)     requests: 0.01ms    removes: 0.00ms    meshes: 0.00ms    looking: 0.01ms    
util.js:183 render internals total 1.99ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.02ms    render: 1.95ms    endFrame: 0.01ms    
util.js:183 world ticks: total 0.03ms (avg, 100 runs)     requests: 0.01ms    removes: 0.00ms    meshes: 0.00ms    looking: 0.01ms    
util.js:183 render internals total 2.89ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.02ms    render: 2.86ms    endFrame: 0.01ms    
react_devtools_backend.js:6 TypeError: Cannot read property 'resume' of null
    at AudioEngine._resumeAudioContext (audioEngine.ts:213)
    at AudioEngine._triggerRunningState (audioEngine.ts:247)
    at AudioEngine.unlock (audioEngine.ts:208)
    at HTMLBodyElement.getAudio (Game.tsx:1249)
r @ react_devtools_backend.js:6
getAudio @ Game.tsx:1255
util.js:183 world ticks: total 1.64ms (avg, 100 runs)     requests: 0.03ms    removes: 0.00ms    meshes: 1.51ms    looking: 0.01ms    remQueue: 0.04ms    addQueue: 0.05ms    
util.js:183 render internals total 3.24ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.01ms    render: 3.21ms    endFrame: 0.01ms    
util.js:183 world ticks: total 2.76ms (avg, 100 runs)     requests: 0.09ms    removes: 0.01ms    meshes: 2.37ms    looking: 0.01ms    remQueue: 0.20ms    addQueue: 0.07ms    
util.js:183 render internals total 2.97ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.01ms    render: 2.94ms    endFrame: 0.01ms    
util.js:183 world ticks: total 3.47ms (avg, 100 runs)     requests: 0.07ms    removes: 0.07ms    meshes: 3.18ms    looking: 0.01ms    remQueue: 0.10ms    addQueue: 0.03ms    
util.js:183 render internals total 3.00ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.01ms    render: 2.98ms    endFrame: 0.01ms    
util.js:183 world ticks: total 2.42ms (avg, 100 runs)     requests: 0.08ms    removes: 0.18ms    meshes: 1.95ms    looking: 0.02ms    remQueue: 0.15ms    addQueue: 0.05ms    
util.js:183 render internals total 3.34ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.01ms    render: 3.31ms    endFrame: 0.01ms    
util.js:183 world ticks: total 3.60ms (avg, 100 runs)     requests: 0.05ms    removes: 0.26ms    meshes: 3.02ms    looking: 0.02ms    remQueue: 0.19ms    addQueue: 0.06ms    
util.js:183 render internals total 3.30ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.01ms    render: 3.27ms    endFrame: 0.01ms    
util.js:183 world ticks: total 3.08ms (avg, 100 runs)     requests: 0.05ms    removes: 0.56ms    meshes: 2.35ms    looking: 0.01ms    remQueue: 0.09ms    addQueue: 0.03ms    
util.js:183 render internals total 3.11ms (avg, 200 runs)     updateCamera: 0.00ms    beginFrame: 0.01ms    render: 3.09ms    endFrame: 0.01ms    
util.js:183 world ticks: total 3.50ms (avg, 100 runs)     requests: 0.05ms    removes: 0.88ms    meshes: 2.44ms    looking: 0.01ms    remQueue: 0.09ms    addQueue: 0.02ms    
Player.tsx:114 #F38630
RobotAvatar.tsx:269 SETTING Color3 {r: 0.9529411764705882, g: 0.5254901960784314, b: 0.18823529411764706}
util.js:183 render internals total 3.14ms (avg, 200 runs)     updateCamera: 0.00ms    beginFrame: 0.01ms    render: 3.12ms    endFrame: 0.01ms    
util.js:183 world ticks: total 3.78ms (avg, 100 runs)     requests: 0.05ms    removes: 0.82ms    meshes: 2.77ms    looking: 0.01ms    remQueue: 0.09ms    addQueue: 0.03ms    
util.js:183 render internals total 3.39ms (avg, 200 runs)     updateCamera: 0.00ms    beginFrame: 0.01ms    render: 3.37ms    endFrame: 0.01ms    
util.js:183 world ticks: total 3.02ms (avg, 100 runs)     requests: 0.05ms    removes: 0.77ms    meshes: 2.07ms    looking: 0.01ms    remQueue: 0.08ms    addQueue: 0.03ms    
util.js:183 render internals total 3.32ms (avg, 200 runs)     updateCamera: 0.00ms    beginFrame: 0.00ms    render: 3.30ms    endFrame: 0.01ms    
util.js:183 world ticks: total 3.04ms (avg, 100 runs)     requests: 0.05ms    removes: 0.71ms    meshes: 2.14ms    looking: 0.01ms    remQueue: 0.09ms    addQueue: 0.03ms    
util.js:183 render internals total 3.07ms (avg, 200 runs)     updateCamera: 0.00ms    beginFrame: 0.00ms    render: 3.06ms    endFrame: 0.01ms    
util.js:183 world ticks: total 2.22ms (avg, 100 runs)     requests: 0.07ms    removes: 0.61ms    meshes: 1.32ms    looking: 0.01ms    remQueue: 0.16ms    addQueue: 0.05ms    
util.js:183 render internals total 3.00ms (avg, 200 runs)     updateCamera: 0.00ms    beginFrame: 0.00ms    render: 2.98ms    endFrame: 0.01ms    
util.js:183 world ticks: total 2.16ms (avg, 100 runs)     requests: 0.05ms    removes: 0.58ms    meshes: 1.40ms    looking: 0.01ms    remQueue: 0.08ms    addQueue: 0.02ms    
util.js:183 render internals total 2.92ms (avg, 200 runs)     updateCamera: 0.00ms    beginFrame: 0.00ms    render: 2.90ms    endFrame: 0.01ms    
hot-dev-client.js:64 [HMR] bundle rebuilding
util.js:183 world ticks: total 2.15ms (avg, 100 runs)     requests: 0.06ms    removes: 0.59ms    meshes: 1.39ms    looking: 0.01ms    remQueue: 0.07ms    addQueue: 0.02ms    
util.js:183 render internals total 2.75ms (avg, 200 runs)     updateCamera: 0.00ms    beginFrame: 0.00ms    render: 2.73ms    endFrame: 0.01ms    
util.js:183 world ticks: total 1.84ms (avg, 100 runs)     requests: 0.05ms    removes: 0.60ms    meshes: 1.05ms    looking: 0.01ms    remQueue: 0.10ms    addQueue: 0.03ms    
util.js:183 render internals total 2.59ms (avg, 200 runs)     updateCamera: 0.00ms    beginFrame: 0.00ms    render: 2.58ms    endFrame: 0.01ms    
util.js:183 world ticks: total 1.87ms (avg, 100 runs)     requests: 0.06ms    removes: 0.63ms    meshes: 1.06ms    looking: 0.01ms    remQueue: 0.07ms    addQueue: 0.02ms    
util.js:183 render internals total 2.38ms (avg, 200 runs)     updateCamera: 0.00ms    beginFrame: 0.00ms    render: 2.36ms    endFrame: 0.01ms    
util.js:183 world ticks: total 0.64ms (avg, 100 runs)     requests: 0.01ms    removes: 0.00ms    meshes: 0.60ms    looking: 0.02ms    
util.js:183 render internals total 2.37ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.00ms    render: 2.35ms    endFrame: 0.01ms    
noa.world.report()
world.js:653 World report - playerChunkLoaded:  true
world.js:693   known:      2373    exist: 2373 full: 0     empty: 1733 surr: 1310  times meshed: avg 3.08  max 6  min 0
world.js:693   to request: 0       exist: 0    full: 0     empty: 0    surr: 0     
world.js:693   to remove:  0       exist: 0    full: 0     empty: 0    surr: 0     
world.js:693   creating:   0       exist: 0    full: 0     empty: 0    surr: 0     
world.js:693   to mesh:    0       exist: 0    full: 0     empty: 0    surr: 0     
```


Running around for about 90 seconds with `chunkAddDistance` set to `12`:
```
world ticks: total 3.44ms (avg, 100 runs)     remQueue: 0.30ms    addQueue: 0.59ms    requests: 0.17ms    removes: 0.19ms    meshes: 2.17ms    looking: 0.01ms    
util.js:183 render internals total 2.99ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.01ms    render: 2.96ms    endFrame: 0.01ms    
util.js:183 world ticks: total 2.52ms (avg, 100 runs)     requests: 0.14ms    removes: 0.31ms    meshes: 1.34ms    looking: 0.01ms    remQueue: 0.35ms    addQueue: 0.36ms    
util.js:183 render internals total 1.74ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.01ms    render: 1.72ms    endFrame: 0.00ms    
util.js:183 world ticks: total 3.20ms (avg, 100 runs)     requests: 0.13ms    removes: 0.32ms    meshes: 1.83ms    looking: 0.01ms    remQueue: 0.46ms    addQueue: 0.44ms    
util.js:183 render internals total 1.90ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.01ms    render: 1.87ms    endFrame: 0.01ms    
util.js:183 world ticks: total 2.34ms (avg, 100 runs)     requests: 0.14ms    removes: 0.37ms    meshes: 1.23ms    looking: 0.01ms    remQueue: 0.31ms    addQueue: 0.28ms    
util.js:183 render internals total 1.85ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.01ms    render: 1.82ms    endFrame: 0.01ms    
util.js:183 world ticks: total 1.58ms (avg, 100 runs)     requests: 0.13ms    removes: 0.10ms    meshes: 1.15ms    looking: 0.01ms    remQueue: 0.10ms    addQueue: 0.10ms    
util.js:183 render internals total 2.12ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.01ms    render: 2.10ms    endFrame: 0.01ms    
util.js:183 world ticks: total 3.04ms (avg, 100 runs)     requests: 0.11ms    removes: 0.47ms    meshes: 1.64ms    looking: 0.01ms    remQueue: 0.39ms    addQueue: 0.41ms    
util.js:183 render internals total 2.00ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.01ms    render: 1.97ms    endFrame: 0.01ms    
util.js:183 world ticks: total 3.48ms (avg, 100 runs)     remQueue: 0.57ms    addQueue: 0.52ms    requests: 0.12ms    removes: 0.80ms    meshes: 1.46ms    looking: 0.01ms    
util.js:183 render internals total 2.10ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.01ms    render: 2.08ms    endFrame: 0.01ms    
util.js:183 world ticks: total 2.88ms (avg, 100 runs)     requests: 0.09ms    removes: 0.50ms    meshes: 1.44ms    looking: 0.01ms    remQueue: 0.42ms    addQueue: 0.42ms    
util.js:183 render internals total 1.80ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.01ms    render: 1.78ms    endFrame: 0.01ms    
util.js:183 world ticks: total 1.71ms (avg, 100 runs)     requests: 0.08ms    removes: 0.25ms    meshes: 1.02ms    looking: 0.01ms    remQueue: 0.18ms    addQueue: 0.18ms    
util.js:183 render internals total 3.45ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.01ms    render: 3.43ms    endFrame: 0.01ms    
util.js:183 world ticks: total 1.41ms (avg, 100 runs)     requests: 0.10ms    removes: 0.24ms    meshes: 0.68ms    looking: 0.01ms    remQueue: 0.19ms    addQueue: 0.19ms    
util.js:183 render internals total 4.80ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.01ms    render: 4.78ms    endFrame: 0.01ms    
util.js:183 world ticks: total 1.47ms (avg, 100 runs)     requests: 0.07ms    removes: 0.28ms    meshes: 0.73ms    looking: 0.01ms    remQueue: 0.18ms    addQueue: 0.18ms    
util.js:183 render internals total 3.88ms (avg, 200 runs)     updateCamera: 0.01ms    beginFrame: 0.02ms    render: 3.85ms    endFrame: 0.01ms    
util.js:183 world ticks: total 1.53ms (avg, 100 runs)     requests: 0.08ms    removes: 0.31ms    meshes: 0.80ms    looking: 0.01ms    remQueue: 0.17ms    addQueue: 0.16ms    
util.js:183 render internals total 3.76ms (avg, 200 runs)     updateCamera: 0.00ms    beginFrame: 0.01ms    render: 3.74ms    endFrame: 0.01ms    
util.js:183 world ticks: total 1.98ms (avg, 100 runs)     requests: 0.07ms    removes: 0.48ms    meshes: 1.09ms    looking: 0.01ms    remQueue: 0.14ms    addQueue: 0.18ms    
util.js:183 render internals total 3.28ms (avg, 200 runs)     updateCamera: 0.00ms    beginFrame: 0.01ms    render: 3.27ms    endFrame: 0.01ms    
util.js:183 world ticks: total 2.84ms (avg, 100 runs)     requests: 0.08ms    removes: 0.78ms    meshes: 1.30ms    looking: 0.01ms    remQueue: 0.33ms    addQueue: 0.35ms    
util.js:183 render internals total 3.49ms (avg, 200 runs)     updateCamera: 0.00ms    beginFrame: 0.01ms    render: 3.47ms    endFrame: 0.01ms    
util.js:183 world ticks: total 3.64ms (avg, 100 runs)     requests: 0.09ms    removes: 1.14ms    meshes: 1.31ms    looking: 0.01ms    remQueue: 0.56ms    addQueue: 0.54ms    
util.js:183 render internals total 3.56ms (avg, 200 runs)     updateCamera: 0.00ms    beginFrame: 0.00ms    render: 3.55ms    endFrame: 0.01ms    
util.js:183 world ticks: total 3.01ms (avg, 100 runs)     requests: 0.07ms    removes: 0.37ms    meshes: 2.23ms    looking: 0.01ms    remQueue: 0.14ms    addQueue: 0.18ms    
util.js:183 render internals total 3.87ms (avg, 200 runs)     updateCamera: 0.00ms    beginFrame: 0.00ms    render: 3.85ms    endFrame: 0.01ms    
util.js:183 world ticks: total 2.52ms (avg, 100 runs)     requests: 0.08ms    removes: 0.81ms    meshes: 0.85ms    looking: 0.01ms    remQueue: 0.39ms    addQueue: 0.37ms    
util.js:183 render internals total 3.59ms (avg, 200 runs)     updateCamera: 0.00ms    beginFrame: 0.00ms    render: 3.58ms    endFrame: 0.01ms    
hot-dev-client.js:64 [HMR] bundle rebuilding
util.js:183 world ticks: total 2.09ms (avg, 100 runs)     requests: 0.08ms    removes: 0.28ms    meshes: 1.30ms    looking: 0.01ms    remQueue: 0.20ms    addQueue: 0.22ms    
util.js:183 render internals total 3.18ms (avg, 200 runs)     updateCamera: 0.00ms    beginFrame: 0.00ms    render: 3.17ms    endFrame: 0.01ms    
noa.world.report()
world.js:653 World report - playerChunkLoaded:  true
world.js:693   known:      7140    exist: 3471 full: 0     empty: 2774 surr: 2001  times meshed: avg 2.42  max 6  min 0
world.js:693   to request: 3663    exist: 0    full: 0     empty: 0    surr: 0     
world.js:693   to remove:  0       exist: 0    full: 0     empty: 0    surr: 0     
world.js:693   creating:   6       exist: 0    full: 0     empty: 0    surr: 0     
world.js:693   to mesh:    8       exist: 8    full: 0     empty: 7    surr: 4     
```

**Comment by Jarred-Sumner** [comment] 2020-05-04 09:14
One thing I just fixed on the server: the world chunk requests server-side were enqueued at the tick rate of the rest of the multiplayer stuff

so that would prevent the server from sending off the chunks to the client until the next tick on the server

and then the client would a few world chunks at once

it feels faster now

**Comment by andyhall** [comment] 2020-05-04 09:55
Okay, gotcha. 7K chunks in memory is pretty high, since the world module needs to look through that array fairly often, and parts of it need to be sorted in some cases. So I think you may see better overall performance with e.g. chunkSize 32 and half the add distance. But it's all down to how your world is set up of course.

For reference, day-to-day I use chunkSize 32 and addDistance of 4-5, and things seem to run okay on old hardware. But as I write this I notice that apparently I switched it to chunk size 64 a few days ago to stress test something, then forgot about it, and I didn't really notice the slowdown. So if you see dramatic FPS drops at smaller sizes there may be other perf issues we can find and fix.

**Comment by andyhall** [comment] 2020-05-04 10:06
Another comment: if the chunk size 16 is dictated by something server side (e.g. something minecraft related), you might find it performs better to abstract that away and have the clients use larger chunks - e.g. the client requests a 32-sized chunk, and the server merges together multiple 16-sized chunks to send over.

One other thing - you may find it useful to run-length-encode the chunks before sending them over the wire. I use [voxel-crunch](https://github.com/mikolalysenko/voxel-crunch) for this, and have found it plenty fast enough to use synchronously, and the compression is great - when a chunk is mostly air or ground it often compresses down to just a few bytes.

**Comment by Jarred-Sumner** [comment] 2020-05-05 02:04
I set `chunkSize` to `32` with a `chunkAddDistance` of `6`, and moved the server code to get the voxel chunks into a separate node worker thread + websocket server so that it doesn't have the multiplayer ticker stuff. I also added voxel-crunch too - thanks for the suggestion.

The chunks fetch faster now, but the game & fps feels slower. 

![image](https://user-images.githubusercontent.com/709451/81029403-a02ff900-8e39-11ea-972a-7e7dcb9443ec.png)

**Comment by andyhall** [comment] 2020-05-05 03:01
Hmm, I'm really not sure why your world is profiling so differently from what I've seen. `mergeSubmeshes` really isn't doing a lot of work, compared to the rest of the meshing process, so my only guess is that v8 is optimizing it really badly in your case for some reason.

Can you see if things look different in, e.g., the testbed world (`npm test` in the `noa-examples` repo)? For reference, here's how that world profiles for me, using chunk size `128` in order to magnify performance issues:

<img width="1054" alt="Screen Shot 2020-05-05 at 11 56 03" src="https://user-images.githubusercontent.com/352373/81031658-efbd0600-8ec7-11ea-919f-ec32641b5dd9.png">

**Comment by Jarred-Sumner** [comment] 2020-05-05 03:20
The hello world example loads great. Is it possible that larger images (32x32) and ~20 active but ~150 registered textures causes issues? Since this world is mostly green blocks

Here it is with a `128` chunkSize:
![image](https://user-images.githubusercontent.com/709451/81032402-80520280-8e44-11ea-8e12-492c65eb2631.png)

**Comment by Jarred-Sumner** [comment] 2020-05-05 03:37
I made some additional changes here and I think it feels fast enough now.

https://github.com/andyhall/noa/commit/75584514171dee5532855ddac340c1b1c6899739?w=1#diff-f04dd27998ae6dd6f014341a0e847960R249

most of these changes are from accidentally running prettier...

but the relevant ones are:
- Switching `Object.keys` with `for (var key in subMeshes) {` when checking whether or not the list of subMeshes is empty

- Pre-allocating the array of materials:
```js
var mats = new Array(results.matIDs.length);
        for (let index = 0; index < results.matIDs.length; index++) {
            let id = results.matIDs[index];
            mats[index] = getTerrainMaterial(id, ignoreMaterials);
        }
```

This change was probably most noticable:
![image](https://user-images.githubusercontent.com/709451/81033084-ffe0d100-8e46-11ea-91c9-3fa67f66329a.png)

**Comment by andyhall** [comment] 2020-05-05 09:01
Hm. Okay, I've pushed another update here. It removes the closure inside `MeshBuilder.build`, and also changes the list of meshes to be an array rather than a hash. Previously the merge logic used `delete` on that hash, which has been known to trigger bad performance in v8 (or, at least to disable optimizations). Can you try it out?

**Comment by Jarred-Sumner** [comment] 2020-05-05 10:15
here's 30 seconds:
![image](https://user-images.githubusercontent.com/709451/81055949-92e92d80-8e7e-11ea-901e-ce489fb548c6.png)

I would say it feels slower, but I also made some changes to picking a little bit ago that might make render slower so I'm not really sure

**Comment by andyhall** [comment] 2020-05-05 12:13
Ok, thanks for checking. It looks like the merge issue is cleared up - the heavy stuff in that profile looks like the stuff that's unavoidable (though it looks like rendering is dominating, so I'm guessing there wasn't any active meshing for most of the time). 

I'll go ahead and mark this issue closed. If you find other specific problems do file a new issue, and thanks for seeing this one through...

**Closed by andyhall** 2020-05-05 12:13 UTC
